language: generic

sudo: false

cache: apt

env:
  global:
    - LSAN_OPTIONS=suppressions=scripts/leak_suppressions.txt
  
install_default: &setup
  - source ./scripts/setup.sh
  - node -v
  - which node
  - clang++ -v
  - which clang++

script_default: &test 
  - make
  - make test

after_script_default: &publish
  - echo ${ASAN_OPTIONS}
  - node-pre-gyp package testpackage ${NPM_FLAGS}
  - source ./scripts/publish.sh

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

matrix:
  include:
    # linux
    - os: linux
      # node_js: "4"
      env: NODE="4" TARGET="Release"
      install: *setup
      script: *test
      after_script: *publish
    - os: linux
      # node_js: "4"
      env: NODE="4" CXXFLAGS="--coverage" LDFLAGS="--coverage" NPM_FLAGS="--debug"
      install: 
        - source ./scripts/setup.sh
        - which llvm-cov
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov" -Z
      script: *test
    - os: osx
      # node_js: "4"
      osx_image: xcode8
      env: NODE="4" TARGET=Release
      install: *setup
      script: *test
      after_script: *publish