language: generic

sudo: false

cache: apt

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++6','libstdc++-5-dev' ]

env:
  global:
   - LSAN_OPTIONS=suppressions=scripts/leak_suppressions.txt

matrix:
  include:
    #- os: osx
    #  osx_image: xcode7.3
    - os: linux
    - os: linux
      env: CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" NPM_FLAGS="--debug" ASAN_OPTIONS=detect_leaks=1 PUBLISHABLE=true
    #- os: linux
    #  env: CXXFLAGS="-fsanitize=integer" LDFLAGS="-fsanitize=integer" NPM_FLAGS="--debug"
    #- os: linux
    #  env: CXXFLAGS="-fsanitize=thread" LDFLAGS="-fsanitize=thread" NPM_FLAGS="--debug"

before_install:
 - source ./scripts/travis_setup.sh
 - node -v
 - which node
 - clang++ -v
 - which clang++

install:
 - ASAN_OPTIONS=detect_leaks=0 npm install --build-from-source ${NPM_FLAGS}

before_script:
  - node-pre-gyp package testpackage ${NPM_FLAGS}
  - |
    if [[ ${PUBLISHABLE} == true ]]; then
      ./scripts/publish.sh;
    fi;

script:
 - echo ${ASAN_OPTIONS}
 - npm test

after_success:
  - |
    if [ -n "${COVERAGE}" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi