language: generic

sudo: false

cache: apt

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++6','libstdc++-5-dev' ]

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
    - os: linux
      env: CXXFLAGS="-fsanitize=address" NPM_FLAGS="--debug"
    - os: linux
      env: CXXFLAGS="-fsanitize=integer" NPM_FLAGS="--debug"
    - os: linux
      env: CXXFLAGS="-fsanitize=thread" NPM_FLAGS="--debug"

before_install:
 - source ./travis_setup.sh
 - node -v
 - which node
 - clang++ -v
 - which clang++

install:
 - npm install --build-from-source ${NPM_FLAGS}

script:
 - npm test

after_success:
  - |
    if [ -n "${COVERAGE}" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi